-- MySQL Script generated by MySQL Workbench
-- Thu May 15 22:25:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gametech_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gametech_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gametech_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gametech_db` ;

-- -----------------------------------------------------
-- Table `gametech_db`.`depositos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gametech_db`.`depositos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ubicacion` VARCHAR(100) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gametech_db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gametech_db`.`productos` (
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(50) NOT NULL,
  `stock_minimo` INT NOT NULL,
  `stock_actual` INT NOT NULL,
  `id_deposito` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `id_deposito` (`id_deposito` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`id_deposito`)
    REFERENCES `gametech_db`.`depositos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gametech_db`.`alertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gametech_db`.`alertas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('CRITICO', 'EXCEDENTE') NOT NULL,
  `producto_codigo` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_emision` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_codigo` (`producto_codigo` ASC) VISIBLE,
  CONSTRAINT `alertas_ibfk_1`
    FOREIGN KEY (`producto_codigo`)
    REFERENCES `gametech_db`.`productos` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gametech_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gametech_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `rol` ENUM('ENCARGADO', 'LOGISTICA', 'ADMINISTRADOR') NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gametech_db`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gametech_db`.`movimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('INGRESO', 'EGRESO', 'AJUSTE') NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `justificacion` TEXT NULL DEFAULT NULL,
  `producto_codigo` VARCHAR(20) NULL DEFAULT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_codigo` (`producto_codigo` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `movimientos_ibfk_1`
    FOREIGN KEY (`producto_codigo`)
    REFERENCES `gametech_db`.`productos` (`codigo`),
  CONSTRAINT `movimientos_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gametech_db`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `gametech_db`;

DELIMITER $$
USE `gametech_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `gametech_db`.`actualizar_stock_y_alerta`
AFTER INSERT ON `gametech_db`.`movimientos`
FOR EACH ROW
BEGIN
  DECLARE stock_actual INT;
  DECLARE stock_minimo INT;
  DECLARE final_stock INT;

  -- Obtener valores actuales
  SELECT p.stock_actual, p.stock_minimo
  INTO stock_actual, stock_minimo
  FROM productos p
  WHERE p.codigo = NEW.producto_codigo;

  -- Calcular cómo quedará el stock luego del movimiento
  SET final_stock = stock_actual + NEW.cantidad;

  -- Actualizar el stock
  UPDATE productos
  SET stock_actual = final_stock
  WHERE codigo = NEW.producto_codigo;

  -- Insertar alerta si el nuevo stock es menor al mínimo
  IF final_stock < stock_minimo THEN
    INSERT INTO alertas (tipo, producto_codigo, fecha_emision)
    VALUES ('CRITICO', NEW.producto_codigo, NOW());
  END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
